name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # - name: Debug OIDC Claims
      #   run: |
      #     echo "Getting OIDC token..."
      
      #     TOKEN=$(curl -s \
      #       -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
      #       "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
      #       | jq -r '.value')
      
      #     echo "$TOKEN"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::122941220195:role/serverless-deployment
          aws-region: us-east-1

      - run: npm install -g serverless@3

      - run: serverless deploy --verbose

      - run: echo "✅ Deployment Complete!"
